### ISSUE TITLE
script tag version of STOCKFISH hangs after first go command

### ISSUE THREAD

**Issue by eguneys** [nmrugg/stockfish.js#1]
```uci
isready
ucinewgame
position fen FEN1
go movetime 1000
ucinewgame
position fen FEN2
go movetime 1000
```

First `go` command works fine and gives the `bestmove`, but second `go` command is ignored.

This happens only in the browser when including a script tag `<script src="stockfish.js"></script>` and creating an instance like this: `var stockfish = STOCKFISH();`

If i use WebWorkers this problem doesn't occur.

**Comment by nmrugg** [comment]
I can't reproduce. Do you have the same issue with the [fast_startup branch](https://github.com/nmrugg/stockfish.js/blob/fast_startup/src/stockfish.js)?

If you do, please post a complete example so that I can check it out.

**Comment by eguneys** [comment]
I didn't compile the project, just used [stockfish.js](https://github.com/nmrugg/stockfish.js/blob/master/src/stockfish.js).

**Comment by nmrugg** [comment]
Since you closed the issue, I assume you got it working. If not, let me know.

The fast_startup branch has also been precompiled.
