### ISSUE TITLE
incorrect evaluation

### ISSUE THREAD

**Issue by indolent-developer** [nmrugg/stockfish.js#16]
The position clearly is a mate in 7 position but stockfish js is not able to find it. only after i play Qe2+ it says its mate in 7.

Position screenshot is here.
https://photos.app.goo.gl/L85dVQS4uhkUFW3A7

**Comment by nmrugg** [comment]
Is it actually a mate? It seems that the computer is getting confused after `1... Qe2+ 2. Kh1 Qf3+` White can escape mate with `Kh2`.

Sometimes the computer sees <a href=https://www.chess.com/analysis-board-editor?fen=6k1/1p2P2p/p2p1Bp1/2p1p3/2P2b1Q/1P4PP/1n2q2K/8%20w%20-%20-%201%202>it</a> as a mate, and sometimes it does not. The binary Stockfish always sees it as about `-4`, so it seems to be an issue with the JS/WASM version.

I'll try to examine this issue further as I work on Stockfish.js 10.

Thanks for the report.

**Comment by nmrugg** [comment]
The update to Stockfish.js 10 is complete. The position you mentioned seems to be evaluated correctly now. Thanks.
