### ISSUE TITLE
How to get started with using Stockfish?

### ISSUE THREAD

**Issue by dsteinman** [nmrugg/stockfish.js#18]
Hi, I don't have any experience with Stockfish, but I am trying to use your stockfish library as the AI engine when playing against "the computer" in a chess game I'm writing.  I need to know how to send the move I make into stockfish, and then for stockfish to send me its next move.  But I'm not sure how or where to find out how to do this and having trouble getting started.  I would appreciate your help.

```
stockfish.postMessage("go depth 15");
```

Now what?  It seems whatever I post returns with "Unknown command".

What protocol should I be looking at?  Is there some sample game data I can feed in?

Thanks for the help!

**Comment by dsteinman** [comment]
You can close this ticket, I snooped around some of the code and found out what I was looking for:

stockfish.postMessage("ucinewgame");
stockfish.postMessage("isready");
stockfish.postMessage("position startpos moves e2e3 d7d6");
stockfish.postMessage("eval");
stockfish.postMessage("d");

And then I can repeat the last 3 commands for every move I want to make or evaluate.  I presume I need to keep my own list of moves and reset and rerun all of them each time.

**Comment by nmrugg** [comment]
Actually, `eval`, just gives a static evaluation of the current position without considering any moves. Use the `go` command, like in your first comment to get the _real_ evaluation. Note also that the `go` command will print out many lines in response. The last one is the recommended move, but you can get the eval in the other lines as it is thinking.

> I presume I need to keep my own list of moves and reset and rerun all of them each time.

Yep.

**Comment by nmrugg** [comment]
See this file for an example https://github.com/nmrugg/stockfish.js/blob/master/test_load_engine.js.

**Comment by dsteinman** [comment]
Thanks a lot for your help by the way, this Stockfish library has been really great to work with.

I also found some of the information here useful for me when I was getting started:

https://chess.stackexchange.com/questions/12580/working-with-uci-protocol-coding
