### ISSUE TITLE
"setoption name Hash value 100" not supported

### ISSUE THREAD

**Issue by dsjoerg** [nmrugg/stockfish.js#2]
I'd like to make stockfish use less memory, primarily so that old devices can handle it more easily.  However when I issue the command "setoption name Hash value 100" I get the following error:

Uncaught abort("Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 67108864, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs.")

I understand the issue a bit, now having read a bit about Emscripten.

What do you think of adding the ALLOW_MEMORY_GROWTH flag to the compile to permit this?  I have no idea how important the optimizations are that this would prevent.

**Comment by dsjoerg** [comment]
By the way, thanks for your excellent work on this!

**Comment by nmrugg** [comment]
Stockfish.js (and Stockfish, I think) default to a 16MB hash, so raising it to 100MB I don't think will help you.

You can set the value smaller without crashing, but the memory usage is fixed by emscripten. So I don't think changing the hash value will help.

**Comment by nmrugg** [comment]
You can look in Makefile for -s TOTAL_MEMORY and try changing that value. I've experimented with this and found that this value made Stockfish.js run the fastest, but if you can come up with another result, please let me know.

Perhaps we could create a 2nd build for low memory devices if you can find something that works better.

As far as ALLOW_MEMORY_GROWTH, I've tried that, and the permanence seems much worse, particularly in Firefox. Emscripten may resolve this issue at some point, and this could be a viable option.

Although, either way, it really shouldn't crash, so I'll look in to fixing that. Thanks.

**Comment by nmrugg** [comment]
Actually, you don't need to recompile it, you can just look in `stockfish.js` for `TOTAL_MEMORY=Module["TOTAL_MEMORY"]||67108864` and change 67108864 to another value. 
It seems like it won't go lower than 33554432, so you could try that and see if it works any better. On the tests I've done, it seems to use the same amount of memory.

**Comment by dsjoerg** [comment]
Thanks for the tips @nmrugg !
