### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by JemiloII** [nmrugg/stockfish.js#21]
I don't need emscripten, I'm not building for the browser. I'm combining this with chess.js so my npc player can pick the next move. This is part of a discord bot, so I create an image of the updated board to send. So how can I use this with node only?

**Comment by nmrugg** [comment]
If by `this`, you mean control an engine via Node, I suggest you look at https://github.com/nmrugg/stockfish.js/blob/master/load_engine.js and https://github.com/nmrugg/stockfish.js/blob/master/test_load_engine.js for an example.

Note that this Stockfish will only return UCI (or LAN) output, which may or may not be compatible with chess.js. An older version also outputted SAN, which can be found <a href=https://github.com/nmrugg/kingdom/blob/master/js/stockfish8.js>here</a>.

**Comment by JemiloII** [comment]
Thanks
