### ISSUE TITLE
How to disable ponder?

### ISSUE THREAD

**Issue by JemiloII** [nmrugg/stockfish.js#23]
Trying to turn ponder off to save some CPU. My bot isn't playing against other bots, just humans. Not quite sure where I'm going wrong with this. It keeps pondering.

```js
const s = require('stockfish/src/stockfish.asm')(); // was loading in my local node repl
s.send = s.postMessage; 
s.onmessage = a => { if (/bestmove/ig.test(a)) { console.log(a); } }; 

// try to default it off
s.send('option name Ponder type check default false'); 

s.send('uciok'); 

//try to manually set it off
s.send('setoption Ponder value false'); 

s.send('ucinewgame'); 
s.send('position startpos');

// move
s.send('go depth 15');
/* returns `bestmove e2e4 ponder e7e6` */
```

**Comment by dsjoerg** [comment]
I think you have to do `setoption name Ponder value false` rather than `setoption Ponder value false`

**Comment by JemiloII** [comment]
So I just tried that. It still is pondering for me :(

**Comment by gbtami** [comment]
In stockfish Ponder is off by default.
Why do you think it's pondering?

**Comment by JemiloII** [comment]
Oh, I just assumed it was pondering since it wrote down`ponder`

**Comment by nmrugg** [comment]
Yes, ponder is off by default.

`ponder e7e6` simply means that the computer thinks it's opponent might reply with `e7e6`. There is no way to disable that without modifying the code (which you are free to do).
