### ISSUE TITLE
Stockfish doesn't exit with node process.

### ISSUE THREAD

**Issue by JemiloII** [nmrugg/stockfish.js#24]
I think I'm starting to understand why my option/setoptions aren't working.

When I start stockfish, it appears to hold game state after I stop and restart.

Making it kinda tricky to use.

**Comment by nmrugg** [comment]
That is not normal engine behavior. The JS version certainly doesn't save state after receiving `quit`.

Perhaps you could provide a way to reproduce this effect.

**Comment by JemiloII** [comment]
Going to close the issue. I can't reproduce it after restarting.
