### ISSUE TITLE
setoption name UCI_LimitStrength and UCI_Elo value no such option

### ISSUE THREAD

**Issue by Simbaclaws** [nmrugg/stockfish.js#28]
Hi there,

I would like to limit the strength of the engine to a specific elo amount, or at least make levels to set how strong the engine is.

How can I achieve this?
So far I can't seem to set these values. Any idea what I could be doing wrong?

Am I sending the wrong UCI command?
I got this idea from the engine-interface.txt

```
setoption name UCI_LimitStrength value true
setoption name UCI_Elo value 1500
```

Please tell me how I can create strength levels.

By the way I really like the engine so far, you did a great job!

**Comment by nmrugg** [comment]
You can use <a href=https://github.com/nmrugg/stockfish.js/blob/007a81ca7d1fbd3abcfaf282a20d2c7c3f338506/src/ucioption.cpp#L80>`Skill Level`</a> (0-20), which is the only setting Stockfish comes with by default.

I have also added <a href=https://github.com/nmrugg/stockfish.js/blob/007a81ca7d1fbd3abcfaf282a20d2c7c3f338506/src/ucioption.cpp#L95>`Skill Level Maximum Error`</a> and <a href=https://github.com/nmrugg/stockfish.js/blob/007a81ca7d1fbd3abcfaf282a20d2c7c3f338506/src/ucioption.cpp#L96>`Skill Level Probability`</a>, which can be further used to tweak the engine's abilities.

E.g.,

```
setoption name Skill Level value 0
setoption name Skill Level Maximum Error value 900
setoption name Skill Level Probability value 10
```

should give you a _very_ weak engine.

**Comment by yanush** [comment]
I'm a bit confused with how to use the other two skill level options.
If I change both "Skill Level Maximum Error" and "Skill Level Probability", wouldn't it affect the original "Skill Level"?
(Sorry for commenting on a closed issue, but I thought it could be relevant for others)

**Comment by tillchess** [comment]
> I'm a bit confused with how to use the other two skill level options.
> If I change both "Skill Level Maximum Error" and "Skill Level Probability", wouldn't it affect the original "Skill Level"?

"Skill Level Maximum Error" and "Skill Level Probability" affects picking the suboptimal move by pick_best . 
 pick_best is called when "Skill Level<20" is set
