### ISSUE TITLE
Support for experimental emscripten pthreads?

### ISSUE THREAD

**Issue by lightbeard** [nmrugg/stockfish.js#3]
Assuming the current stockfish.js implementation uses a single thread - are there any plans to support new emscripten pthreads (only available in Firefox so far):

https://groups.google.com/forum/#!topic/emscripten-discuss/gQQRjajQ6iY
https://github.com/lars-t-hansen/ecmascript_sharedmem

**Comment by nmrugg** [comment]
Interesting. I had not heard of it. It sounds too good to be true. I 
will keep it on my radar.
