### ISSUE TITLE
List of available commands

### ISSUE THREAD

**Issue by ImanimalXI** [nmrugg/stockfish.js#32]
where do I find a list of available cli-commands?

**Comment by andres-lowrie** [comment]
I've been using this 
https://gist.github.com/aliostad/f4470274f39d29b788c1b09519e67372

**Comment by ImanimalXI** [comment]
thank you, that's what i was looking for.

**Comment by nmrugg** [comment]
Note that Stockfish.js supports tab autocompletion. You can find the list here: https://github.com/nmrugg/stockfish.js/blob/master/src/post.js#L276-L313

Other places you can examine: 
https://github.com/nmrugg/stockfish.js/blob/master/src/uci.cpp#L319-L344
https://github.com/nmrugg/stockfish.js/blob/master/src/ucioption.cpp#L67-L97
https://github.com/nmrugg/stockfish.js/blob/master/src/uci.cpp#L193-L222
