### ISSUE TITLE
Upgrade to Stockfish 11

### ISSUE THREAD

**Issue by linrock** [nmrugg/stockfish.js#36]
Stockfish 11 was released in Jan 2020:
https://blog.stockfishchess.org/

**Comment by nmrugg** [comment]
Yep. I'm working on it. It shouldn't be much longer now.

**Comment by vesper8** [comment]
How's it going @nmrugg ? Might as well upgrade to Stockfish 12 now that it's out ;p

Thanks for all your hard work!

**Comment by nmrugg** [comment]
Stockfish 11 is now released. 12 is in the works.

**Comment by vesper8** [comment]
that's awesome @nmrugg ! I updated my project to your newly released Stockfish and everything is working well. I did notice the size grew exponentially and made a new issue about it here https://github.com/nmrugg/stockfish.js/issues/45. Would love to hear your feedback on why the size grew so much

Thank you for the continued maintenance of this package!

**Comment by scchess** [comment]
Has upgrade to SF12 completed? What about SF13 just released today?
