### ISSUE TITLE
Upgrade to Stockfish 7

### ISSUE THREAD

**Issue by PascalPflaum** [nmrugg/stockfish.js#4]
Thanks a lot for this wonderful repo.
Stockfish 7 was released recently.
Would you mind to upgrade?

**Comment by nmrugg** [comment]
Yes, sooner or later. There are a number of patches that need to be back ported, so it will take a little time.

**Comment by ornicar** [comment]
Hi, I'm the developer of [lichess.org](lichess.org), a popular chess server that's entirely free and open source (github.com/ornicar/lila).

We use your work extensively in the [analysis board](http://lichess.org/analysis). Thousands of chess players use it every day, and they are loving it.

So big props and thanks to you. That's a killer feature.

I figured I'd let you know that, should you upgrade stockfish, I would immediately upgrade lichess with it. 

We actually use a fork of stockfish that supports several chess variants: https://github.com/ddugovic/Stockfish. It's almost in sync with stockfish master. Maybe you'd consider compiling that; then lichess could provide local analysis for variants as well.

I know very well what open source means, and I would never dare asking anything more than what you already graciously offered to the chess community. Just letting you know your work is immensely appreciated :)

Cheers,
Thibault

**Comment by pickhardt** [comment]
I noticed that chess.com is using this now as well. For instance: http://betacssjs.chesscomfiles.com/bundles/app/js/vendor/jschessengine/engineworker.db03fd4a.js

They actually have a few other game types that are interesting, like 3+ check (3 checks=win), Crazyhouse, and King of the Hill (king to center 4 squares wins).
