### ISSUE TITLE
use stockfish.js from closed-source website?

### ISSUE THREAD

**Issue by mmcnl** [nmrugg/stockfish.js#42]
@nmrugg Hello and thank you and all contributors so much for the great work on this project! 

I have a licensing question: I am developing a chess education website and would love to be able to use `stockfish.js` (as a web-worker, communicating via the UCI protocol) to add a real-time evaluation feature. But I'm not sure if this is permitted since I'm not (yet) prepared to GPL license the front-end source code for the site (to match stockfish.js).  However I've been reading about the GPLv3 and found [this passage from the GNU FAQ](https://www.gnu.org/licenses/gpl-faq.en.html#GPLInProprietarySystem) 

> in many cases you can distribute the GPL-covered software alongside your proprietary system. To do this validly, you must make sure that the free and nonfree programs communicate at arms length, that they are not combined in a way that would make them effectively a single program.

which makes me wonder if you would consider my js code calling an unmodified `stockfish.js` (as a web-worker via UCI) as sufficiently "arms-length" to be acceptable. From what I've read in various discussions this kind of thing seems to be a bit of a legal gray-zone but since I would not want to do anything disrespectful to the Stockfish community, I wanted to simply ask for guidance and/or permission before proceeding. 

Thank you very much for any input!

**Comment by nmrugg** [comment]
You're fine.

From the same document,

> By contrast, pipes, sockets and command-line arguments are communication mechanisms normally used between two separate programs.

Communicating with stockfish.js via web workers via the UCI protocol falls into this category.

[One of the primary Stockfish devs agrees as well](https://groups.google.com/d/msg/fishcooking/oBuUfSPJlmQ/dfL0JeBwAwAJ).

**Comment by mmcnl** [comment]
Great, thank you @nmrugg for the clarification and the helpful link to the other discussion.

**Comment by vesper8** [comment]
would love to see what you're working on @mmcnl : ) is it live yet?
