### ISSUE TITLE
How to find multiple moves to consider?

### ISSUE THREAD

**Issue by frazereastman** [nmrugg/stockfish.js#49]
How do I make it so stockfish returns multiple moves after an evaluation. I am making a training program and at the moment am using stockfish to find the best move but want stockfish to instead return say the top 3 replies and play one at random.

**Comment by SyntaxBlitz** [comment]
I think you want the [MultiPV option](https://chess.stackexchange.com/questions/12580/working-with-uci-protocol-coding). You'll still only get one `bestmove`, but you'll get multiple `depth n` events, each starting with a different move in the variation line.

```javascript
stockfish.postMessage('setoption name MultiPV value 3');
```

**Comment by nmrugg** [comment]
You need to examine the output stream. You can find an example of how to do it <a href=https://github.com/nmrugg/stockfish.js/blob/master/test_load_engine.js#L76-L95>here</a> using <a href=https://github.com/nmrugg/stockfish.js/blob/master/load_engine.js>load_engine.js</a>.
