### ISSUE TITLE
stockfish.js:41 Uncaught RuntimeError

### ISSUE THREAD

**Issue by datteroandrea** [nmrugg/stockfish.js#60]
I was trying the example in the repository and I have got this error: `Uncaught RuntimeError: abort(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 2e 2e 2f 73 @+0). Build with -s ASSERTIONS=1 for more info.'`  it doesn't let me play

**Comment by eluo28** [comment]
since you closed this ticket mind if I ask if you found a solution?
