### ISSUE TITLE
Will Stockfish ever be able to provide workarounds for SharedArrayBuffer?

### ISSUE THREAD

**Issue by gmcheems** [nmrugg/stockfish.js#65]
I'm aware of the COOP and COEP headers needed to run newer stockfish versions (in order for SharedArrayBuffer to be enabled) but I'm in a situation where that's not possible.

So my question is: are there workarounds for SharedArrayBuffer or will stockfish.js always require that going fowards?

**Comment by nmrugg** [comment]
I know that COOP and COEP headers suck.

Browser vendors are preparing workarounds. Checkout <a href=https://github.com/WICG/anonymous-iframe>credentialless/anonymous iframes</a>. It's in <a href=https://developer.chrome.com/origintrials/#/view_trial/2518638091606949889>origin trials</a> now. This will likely be the way to fix this issue going forward.

You can fallback to an <a href=https://github.com/nmrugg/stockfish.js/tree/Stockfish11>older Stockfish</a> version for browsers that are unsupported.

I think it is unlikely that there will be another Stockfish.js that does not use SharedArrayBuffer. But I'm open to suggestions/contributions.
