### ISSUE TITLE
More precisions about options.

### ISSUE THREAD

**Issue by clementvp** [nmrugg/stockfish.js#7]
Hi and thx for the great work ;)
Can i have more details about theses options:
option name Skill Level Maximum Error type spin default 2 min 1 max 100
option name Skill Level Probability type spin default 128 min 1 max 1000
?
What Probability is for ?

**Comment by nmrugg** [comment]
Sorry for letting this get away. `Probability` is a factor in Stockfish's internal algorithm that determines  how likely the engine will  blunder (and by how much). Lower values mean *more* probable to blunder.
