### ISSUE TITLE
NPM package missing output file

### ISSUE THREAD

**Issue by samuraitruong** [nmrugg/stockfish.js#81]
there no stockfish.js and stockfish.wasm in the package when install from npm

I tried to build it from source but nothing work, If anyone have working version of v16 please share. Thanks

**Comment by samuraitruong** [comment]
nvm, I found the way to get it works,

**Comment by phillipl21** [comment]
Hey there, how did you get it to work? I installed emcc and tried running "./build.js", but it didn't output any files like "stockfish.js"

**Comment by samuraitruong** [comment]
@phillipl21  I end up with using docker to build it. MACOS build does not works properly.
